/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SetPasswordRouteImport } from './routes/set-password'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ProfessionalsRouteImport } from './routes/professionals'
import { Route as MarketingRouteImport } from './routes/marketing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LandingDemoRouteImport } from './routes/landing-demo'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as GestionRouteImport } from './routes/gestion'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as CashRegisterLiquidacionesCompactoRouteImport } from './routes/cash-register-liquidaciones-compacto'
import { Route as CashRegisterRouteImport } from './routes/cash-register'
import { Route as AppointmentsRouteImport } from './routes/appointments'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as AdvisorlRouteImport } from './routes/advisorl'
import { Route as AdvisorRouteImport } from './routes/advisor'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReservarSlugRouteImport } from './routes/reservar/$slug'
import { Route as NegocioSlugRouteImport } from './routes/negocio/$slug'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SetPasswordRoute = SetPasswordRouteImport.update({
  id: '/set-password',
  path: '/set-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfessionalsRoute = ProfessionalsRouteImport.update({
  id: '/professionals',
  path: '/professionals',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingRoute = MarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingDemoRoute = LandingDemoRouteImport.update({
  id: '/landing-demo',
  path: '/landing-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const GestionRoute = GestionRouteImport.update({
  id: '/gestion',
  path: '/gestion',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const CashRegisterLiquidacionesCompactoRoute =
  CashRegisterLiquidacionesCompactoRouteImport.update({
    id: '/cash-register-liquidaciones-compacto',
    path: '/cash-register-liquidaciones-compacto',
    getParentRoute: () => rootRouteImport,
  } as any)
const CashRegisterRoute = CashRegisterRouteImport.update({
  id: '/cash-register',
  path: '/cash-register',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentsRoute = AppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvisorlRoute = AdvisorlRouteImport.update({
  id: '/advisorl',
  path: '/advisorl',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvisorRoute = AdvisorRouteImport.update({
  id: '/advisor',
  path: '/advisor',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservarSlugRoute = ReservarSlugRouteImport.update({
  id: '/reservar/$slug',
  path: '/reservar/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const NegocioSlugRoute = NegocioSlugRouteImport.update({
  id: '/negocio/$slug',
  path: '/negocio/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/advisor': typeof AdvisorRoute
  '/advisorl': typeof AdvisorlRoute
  '/agenda': typeof AgendaRoute
  '/appointments': typeof AppointmentsRoute
  '/cash-register': typeof CashRegisterRoute
  '/cash-register-liquidaciones-compacto': typeof CashRegisterLiquidacionesCompactoRoute
  '/clients': typeof ClientsRoute
  '/dashboard': typeof DashboardRoute
  '/gestion': typeof GestionRoute
  '/inventory': typeof InventoryRoute
  '/landing-demo': typeof LandingDemoRoute
  '/login': typeof LoginRoute
  '/marketing': typeof MarketingRoute
  '/professionals': typeof ProfessionalsRoute
  '/reports': typeof ReportsRoute
  '/services': typeof ServicesRoute
  '/set-password': typeof SetPasswordRoute
  '/settings': typeof SettingsRoute
  '/negocio/$slug': typeof NegocioSlugRoute
  '/reservar/$slug': typeof ReservarSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/advisor': typeof AdvisorRoute
  '/advisorl': typeof AdvisorlRoute
  '/agenda': typeof AgendaRoute
  '/appointments': typeof AppointmentsRoute
  '/cash-register': typeof CashRegisterRoute
  '/cash-register-liquidaciones-compacto': typeof CashRegisterLiquidacionesCompactoRoute
  '/clients': typeof ClientsRoute
  '/dashboard': typeof DashboardRoute
  '/gestion': typeof GestionRoute
  '/inventory': typeof InventoryRoute
  '/landing-demo': typeof LandingDemoRoute
  '/login': typeof LoginRoute
  '/marketing': typeof MarketingRoute
  '/professionals': typeof ProfessionalsRoute
  '/reports': typeof ReportsRoute
  '/services': typeof ServicesRoute
  '/set-password': typeof SetPasswordRoute
  '/settings': typeof SettingsRoute
  '/negocio/$slug': typeof NegocioSlugRoute
  '/reservar/$slug': typeof ReservarSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/advisor': typeof AdvisorRoute
  '/advisorl': typeof AdvisorlRoute
  '/agenda': typeof AgendaRoute
  '/appointments': typeof AppointmentsRoute
  '/cash-register': typeof CashRegisterRoute
  '/cash-register-liquidaciones-compacto': typeof CashRegisterLiquidacionesCompactoRoute
  '/clients': typeof ClientsRoute
  '/dashboard': typeof DashboardRoute
  '/gestion': typeof GestionRoute
  '/inventory': typeof InventoryRoute
  '/landing-demo': typeof LandingDemoRoute
  '/login': typeof LoginRoute
  '/marketing': typeof MarketingRoute
  '/professionals': typeof ProfessionalsRoute
  '/reports': typeof ReportsRoute
  '/services': typeof ServicesRoute
  '/set-password': typeof SetPasswordRoute
  '/settings': typeof SettingsRoute
  '/negocio/$slug': typeof NegocioSlugRoute
  '/reservar/$slug': typeof ReservarSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/advisor'
    | '/advisorl'
    | '/agenda'
    | '/appointments'
    | '/cash-register'
    | '/cash-register-liquidaciones-compacto'
    | '/clients'
    | '/dashboard'
    | '/gestion'
    | '/inventory'
    | '/landing-demo'
    | '/login'
    | '/marketing'
    | '/professionals'
    | '/reports'
    | '/services'
    | '/set-password'
    | '/settings'
    | '/negocio/$slug'
    | '/reservar/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/advisor'
    | '/advisorl'
    | '/agenda'
    | '/appointments'
    | '/cash-register'
    | '/cash-register-liquidaciones-compacto'
    | '/clients'
    | '/dashboard'
    | '/gestion'
    | '/inventory'
    | '/landing-demo'
    | '/login'
    | '/marketing'
    | '/professionals'
    | '/reports'
    | '/services'
    | '/set-password'
    | '/settings'
    | '/negocio/$slug'
    | '/reservar/$slug'
  id:
    | '__root__'
    | '/'
    | '/advisor'
    | '/advisorl'
    | '/agenda'
    | '/appointments'
    | '/cash-register'
    | '/cash-register-liquidaciones-compacto'
    | '/clients'
    | '/dashboard'
    | '/gestion'
    | '/inventory'
    | '/landing-demo'
    | '/login'
    | '/marketing'
    | '/professionals'
    | '/reports'
    | '/services'
    | '/set-password'
    | '/settings'
    | '/negocio/$slug'
    | '/reservar/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdvisorRoute: typeof AdvisorRoute
  AdvisorlRoute: typeof AdvisorlRoute
  AgendaRoute: typeof AgendaRoute
  AppointmentsRoute: typeof AppointmentsRoute
  CashRegisterRoute: typeof CashRegisterRoute
  CashRegisterLiquidacionesCompactoRoute: typeof CashRegisterLiquidacionesCompactoRoute
  ClientsRoute: typeof ClientsRoute
  DashboardRoute: typeof DashboardRoute
  GestionRoute: typeof GestionRoute
  InventoryRoute: typeof InventoryRoute
  LandingDemoRoute: typeof LandingDemoRoute
  LoginRoute: typeof LoginRoute
  MarketingRoute: typeof MarketingRoute
  ProfessionalsRoute: typeof ProfessionalsRoute
  ReportsRoute: typeof ReportsRoute
  ServicesRoute: typeof ServicesRoute
  SetPasswordRoute: typeof SetPasswordRoute
  SettingsRoute: typeof SettingsRoute
  NegocioSlugRoute: typeof NegocioSlugRoute
  ReservarSlugRoute: typeof ReservarSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/set-password': {
      id: '/set-password'
      path: '/set-password'
      fullPath: '/set-password'
      preLoaderRoute: typeof SetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/professionals': {
      id: '/professionals'
      path: '/professionals'
      fullPath: '/professionals'
      preLoaderRoute: typeof ProfessionalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing': {
      id: '/marketing'
      path: '/marketing'
      fullPath: '/marketing'
      preLoaderRoute: typeof MarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing-demo': {
      id: '/landing-demo'
      path: '/landing-demo'
      fullPath: '/landing-demo'
      preLoaderRoute: typeof LandingDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gestion': {
      id: '/gestion'
      path: '/gestion'
      fullPath: '/gestion'
      preLoaderRoute: typeof GestionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cash-register-liquidaciones-compacto': {
      id: '/cash-register-liquidaciones-compacto'
      path: '/cash-register-liquidaciones-compacto'
      fullPath: '/cash-register-liquidaciones-compacto'
      preLoaderRoute: typeof CashRegisterLiquidacionesCompactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cash-register': {
      id: '/cash-register'
      path: '/cash-register'
      fullPath: '/cash-register'
      preLoaderRoute: typeof CashRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointments': {
      id: '/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advisorl': {
      id: '/advisorl'
      path: '/advisorl'
      fullPath: '/advisorl'
      preLoaderRoute: typeof AdvisorlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advisor': {
      id: '/advisor'
      path: '/advisor'
      fullPath: '/advisor'
      preLoaderRoute: typeof AdvisorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservar/$slug': {
      id: '/reservar/$slug'
      path: '/reservar/$slug'
      fullPath: '/reservar/$slug'
      preLoaderRoute: typeof ReservarSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/negocio/$slug': {
      id: '/negocio/$slug'
      path: '/negocio/$slug'
      fullPath: '/negocio/$slug'
      preLoaderRoute: typeof NegocioSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdvisorRoute: AdvisorRoute,
  AdvisorlRoute: AdvisorlRoute,
  AgendaRoute: AgendaRoute,
  AppointmentsRoute: AppointmentsRoute,
  CashRegisterRoute: CashRegisterRoute,
  CashRegisterLiquidacionesCompactoRoute:
    CashRegisterLiquidacionesCompactoRoute,
  ClientsRoute: ClientsRoute,
  DashboardRoute: DashboardRoute,
  GestionRoute: GestionRoute,
  InventoryRoute: InventoryRoute,
  LandingDemoRoute: LandingDemoRoute,
  LoginRoute: LoginRoute,
  MarketingRoute: MarketingRoute,
  ProfessionalsRoute: ProfessionalsRoute,
  ReportsRoute: ReportsRoute,
  ServicesRoute: ServicesRoute,
  SetPasswordRoute: SetPasswordRoute,
  SettingsRoute: SettingsRoute,
  NegocioSlugRoute: NegocioSlugRoute,
  ReservarSlugRoute: ReservarSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
